// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_xOcQsgyofxHi8oA72FsYWy1_fYQajwg',
    appId: '1:38595082311:web:6a23f35cb42eb8ffe99962',
    messagingSenderId: '38595082311',
    projectId: 'chelan-f0ea9',
    authDomain: 'chelan-f0ea9.firebaseapp.com',
    storageBucket: 'chelan-f0ea9.appspot.com',
    measurementId: 'G-60GHHC5F92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQSx0yiyH-9z-6aLYJrgalPVB9JnSRxlY',
    appId: '1:38595082311:android:8624dba7b7d5f6f5e99962',
    messagingSenderId: '38595082311',
    projectId: 'chelan-f0ea9',
    storageBucket: 'chelan-f0ea9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD961JHrBIFrYRzi8WJL3JfG5ovh0PzzIw',
    appId: '1:38595082311:ios:71dd208f92a5ac59e99962',
    messagingSenderId: '38595082311',
    projectId: 'chelan-f0ea9',
    storageBucket: 'chelan-f0ea9.appspot.com',
    iosBundleId: 'lenche.project.lenche',
  );
}
